name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: El check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        run: npm install --no-audit --no-fund --no-optional
      - name: Lint
        run: npm run eslint 
      - name: Test
        run: npm test 
      - name: E2N cypress-io/github-action@v6
        uses: cypress-io/github-action@v6 
        with: 
           command: npm run test:e2e 
           start: npm run start-test
           wait-on: http://localhost:5000